script update

diff --git a/.github/workflows/cd_http-server.yml b/.github/workflows/cd_http-server.yml
--- a/.github/workflows/cd_http-server.yml
+++ b/.github/workflows/cd_http-server.yml
@@ -45,13 +45,13 @@ jobs:
             cd mindsketch
 
             echo "Pulling latest image from Docker Hub..."
-            docker pull abhoy21/mindsketch-http-server:${GITHUB_SHA} || {
-                echo "Error: Failed to pull latest image from Docker Hub"
-                exit 1
+            docker pull abhoy21/mindsketch-http-server:${{ github. sha }} || {
+              echo "Error: Failed to pull latest image from Docker Hub"
+              exit 1
             }
 
             echo "Running docker container..."
-            docker run -d -p 8000:8000 --name http-server -e NODE_ENV=production -e DATABASE_URL="${DATABASE_URL}" -e JWT_SECRET="${JWT_SECRET}" -e GEMINI_API_KEY="${GEMINI_API_KEY}" -e ACCESS_TOKEN_EXPIRES_IN="${ACCESS_TOKEN_EXPIRES_IN}" -e REFRESH_TOKEN_EXPIRES_IN="${REFRESH_TOKEN_EXPIRES_IN}" abhoy21/mindsketch-http-server:${GITHUB_SHA} || {
-                echo "Error: Failed to run docker container"
-                exit 1
+              docker run -d -p 8000:8000 --name http-server -e NODE_ENV=production -e DATABASE_URL=${{ secrets.DATABASE_URL }} -e JWT_SECRET=${{ secrets.JWT_SECRET }} -e GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }} -e ACCESS_TOKEN_EXPIRES_IN=${{ secrets.ACCESS_TOKEN_EXPIRES_IN }} -e REFRESH_TOKEN_EXPIRES_IN=${{ secrets.REFRESH_TOKEN_EXPIRES_IN }} abhoy21/mindsketch-http-server:${{ github.sha }} || {
+              echo "Error: Failed to run docker container"
+              exit 1
             }
diff --git a/.github/workflows/cd_web.yml b/.github/workflows/cd_web.yml
--- a/.github/workflows/cd_web.yml
+++ b/.github/workflows/cd_web.yml
@@ -45,13 +45,13 @@ jobs:
             cd mindsketch
 
             echo "Pulling latest image from Docker Hub..."
-            docker pull abhoy21/mindsketch-web:${GITHUB_SHA} || {
-                echo "Error: Failed to pull latest image from Docker Hub"
-                exit 1
+            docker pull abhoy21/mindsketch-web:${{ github.sha }} || {
+            echo "Error: Failed to pull latest image from Docker Hub"
+            exit 1
             }
 
             echo "Running docker container..."
-            docker run -d -p 8000:8000 --name web -e NODE_ENV=production -e NEXT_PUBLIC_HTTP_URL="${NEXT_PUBLIC_HTTP_URL}" -e NEXT_PUBLIC_WS_URL="${NEXT_PUBLIC_WS_URL}" abhoy21/mindsketch-web:${GITHUB_SHA} || {
-                echo "Error: Failed to run docker container"
-                exit 1
+            docker run -d -p 8000:8000 --name web -e NODE_ENV=production -e NEXT_PUBLIC_HTTP_URL=${{secrets.NEXT_PUBLIC_HTTP_URL}} -e NEXT_PUBLIC_WS_URL=${{secrets.NEXT_PUBLIC_WS_URL}} abhoy21/mindsketch-web:${{ github.sha }} || {
+            echo "Error: Failed to run docker container"
+            exit 1
             }
diff --git a/.github/workflows/cd_worker.yml b/.github/workflows/cd_worker.yml
--- a/.github/workflows/cd_worker.yml
+++ b/.github/workflows/cd_worker.yml
@@ -45,13 +45,13 @@ jobs:
             cd mindsketch
 
             echo "Pulling latest image from Docker Hub..."
-            docker pull abhoy21/mindsketch-worker:${GITHUB_SHA} || {
-                echo "Error: Failed to pull latest image from Docker Hub"
-                exit 1
+            docker pull abhoy21/mindsketch-worker:${{ github.sha }} || {
+            echo "Error: Failed to pull latest image from Docker Hub"
+            exit 1
             }
 
             echo "Running docker container..."
-            docker run -d --name worker -e NODE_ENV=production -e DATABASE_URL="${DATABASE_URL}" -e REDIS_URL="${REDIS_URL}" abhoy21/mindsketch-worker:${GITHUB_SHA} || {
-                echo "Error: Failed to run docker container"
-                exit 1
+            docker run -d -p 8000:8000 --name web -e NODE_ENV=production -e DATABASE_URL=${{secrets.DATABASE_URL}} -e REDIS_URL=${{secrets.REDIS_URL}} abhoy21/mindsketch-worker:${{ github.sha }} || {
+            echo "Error: Failed to run docker container"
+            exit 1
             }
