docker cicd

diff --git a/.github/workflows/cd_worker.yml b/.github/workflows/cd_worker.yml
--- a/.github/workflows/cd_worker.yml
+++ b/.github/workflows/cd_worker.yml
@@ -1,75 +1,75 @@
-# name: Deploy the Worker
-# on:
-#   push:
-#     branches:
-#       - main
-# jobs:
-#   build:
-#     runs-on: ubuntu-latest
-#     steps:
-#       - name: Checkout the code
-#         uses: actions/checkout@v4
+name: Deploy the Worker
+on:
+  push:
+    branches:
+      - main
+jobs:
+  build:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout the code
+        uses: actions/checkout@v4
 
-#       - name: Docker Login
-#         uses: docker/login-action@v3
-#         with:
-#           username: ${{ secrets.DOCKERHUB_USERNAME }}
-#           password: ${{ secrets.DOCKERHUB_TOKEN }}
+      - name: Docker Login
+        uses: docker/login-action@v3
+        with:
+          username: ${{ secrets.DOCKERHUB_USERNAME }}
+          password: ${{ secrets.DOCKERHUB_TOKEN }}
 
-#       - name: Set up QEMU
-#         uses: docker/setup-qemu-action@v3
+      - name: Set up QEMU
+        uses: docker/setup-qemu-action@v3
 
-#       - name: Build and push the Docker image
-#         uses: docker/build-push-action@v6
-#         with:
-#           context: .
-#           file: ./docker/Dockerfile.worker
-#           push: true
-#           tags: abhoy21/mindsketch-worker:${{ github.sha }}
+      - name: Build and push the Docker image
+        uses: docker/build-push-action@v6
+        with:
+          context: .
+          file: ./docker/Dockerfile.worker
+          push: true
+          tags: abhoy21/mindsketch-worker:${{ github.sha }}
 
-#       - name: Deploy to VM
-#         uses: appleboy/ssh-action@v1.2.1
-#         with:
-#           host: ${{ secrets.HOST }}
-#           username: azureuser
-#           key: ${{ secrets.PRIVATE_SSH_KEY }}
-#           port: 22
-#           script: |
-#             #!/bin/bash
-#             if [ ! -d "mindsketch" ]; then
-#                 echo "Creating mindsketch directory..."
-#                 mkdir mindsketch
-#             fi
+      - name: Deploy to VM
+        uses: appleboy/ssh-action@v1.2.1
+        with:
+          host: ${{ secrets.HOST }}
+          username: azureuser
+          key: ${{ secrets.PRIVATE_SSH_KEY }}
+          port: 22
+          script: |
+            #!/bin/bash
+            if [ ! -d "mindsketch" ]; then
+                echo "Creating mindsketch directory..."
+                mkdir mindsketch
+            fi
 
-#             echo "Changing directory to mindsketch..."
-#             cd mindsketch
+            echo "Changing directory to mindsketch..."
+            cd mindsketch
 
-#             echo "Pulling latest image from Docker Hub..."
-#             sudo docker pull abhoy21/mindsketch-worker:${{ github.sha }} || {
-#             echo "Error: Failed to pull latest image from Docker Hub"
-#             exit 1
-#             }
+            echo "Pulling latest image from Docker Hub..."
+            sudo docker pull abhoy21/mindsketch-worker:${{ github.sha }} || {
+            echo "Error: Failed to pull latest image from Docker Hub"
+            exit 1
+            }
 
-#             # Check if Redis container is running
-#             echo "Checking if Redis container is running..."
-#             if ! sudo docker ps -q -f name=redis; then
-#                 echo "Redis container is not running. Starting Redis..."
-#                 sudo docker run -d --name redis -p 6379:6379 redis || {
-#                 echo "Error: Failed to start Redis container"
-#                 exit 1
-#                 }
-#             else
-#                 echo "Redis container is already running."
-#             fi
+            # Check if Redis container is running
+            echo "Checking if Redis container is running..."
+            if ! sudo docker ps -q -f name=redis; then
+                echo "Redis container is not running. Starting Redis..."
+                sudo docker run -d --name redis -p 6379:6379 redis || {
+                echo "Error: Failed to start Redis container"
+                exit 1
+                }
+            else
+                echo "Redis container is already running."
+            fi
 
-#             echo "Stopping existing worker container if it exists..."
-#             sudo docker stop worker 2>/dev/null || true
+            echo "Stopping existing worker container if it exists..."
+            sudo docker stop worker 2>/dev/null || true
 
-#             echo "Removing existing worker container if it exists..."
-#             sudo docker rm worker 2>/dev/null || true
+            echo "Removing existing worker container if it exists..."
+            sudo docker rm worker 2>/dev/null || true
 
-#             echo "Running worker docker container WORKER..."
-#             sudo docker run -d --name worker -e DATABASE_URL=${{secrets.DATABASE_URL}} -e REDIS_URL=${{secrets.REDIS_URL}} abhoy21/mindsketch-worker:${{ github.sha }} || {
-#             echo "Error: Failed to run worker container"
-#             exit 1
-#             }
+            echo "Running worker docker container WORKER..."
+            sudo docker run -d --name worker -e DATABASE_URL=${{secrets.DATABASE_URL}} -e REDIS_URL=${{secrets.REDIS_URL}} abhoy21/mindsketch-worker:${{ github.sha }} || {
+            echo "Error: Failed to run worker container"
+            exit 1
+            }
