docker cicd try

diff --git a/.github/workflows/cd_ws-server.yml b/.github/workflows/cd_ws-server.yml
--- a/.github/workflows/cd_ws-server.yml
+++ b/.github/workflows/cd_ws-server.yml
@@ -1,63 +1,63 @@
-# name: Deploy the WebSocket server
-# on:
-#   push:
-#     branches:
-#       - main
-# jobs:
-#   build:
-#     runs-on: ubuntu-latest
-#     steps:
-#       - name: Checkout the code
-#         uses: actions/checkout@v4
+name: Deploy the WebSocket server
+on:
+  push:
+    branches:
+      - main
+jobs:
+  build:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout the code
+        uses: actions/checkout@v4
 
-#       - name: Docker Login
-#         uses: docker/login-action@v3
-#         with:
-#           username: ${{ secrets.DOCKERHUB_USERNAME }}
-#           password: ${{ secrets.DOCKERHUB_TOKEN }}
+      - name: Docker Login
+        uses: docker/login-action@v3
+        with:
+          username: ${{ secrets.DOCKERHUB_USERNAME }}
+          password: ${{ secrets.DOCKERHUB_TOKEN }}
 
-#       - name: Set up QEMU
-#         uses: docker/setup-qemu-action@v3
+      - name: Set up QEMU
+        uses: docker/setup-qemu-action@v3
 
-#       - name: Build and push the Docker image
-#         uses: docker/build-push-action@v6
-#         with:
-#           context: .
-#           file: ./docker/Dockerfile.ws-server
-#           push: true
-#           tags: abhoy21/mindsketch-ws-server:${{ github.sha }}
+      - name: Build and push the Docker image
+        uses: docker/build-push-action@v6
+        with:
+          context: .
+          file: ./docker/Dockerfile.ws-server
+          push: true
+          tags: abhoy21/mindsketch-ws-server:${{ github.sha }}
 
-#       - name: Deploy to VM
-#         uses: appleboy/ssh-action@v1.2.1
-#         with:
-#           host: ${{ secrets.HOST }}
-#           username: azureuser
-#           key: ${{ secrets.PRIVATE_SSH_KEY }}
-#           port: 22
-#           script: |
-#             #!/bin/bash
-#             if [ ! -d "mindsketch" ]; then
-#                 echo "Creating mindsketch directory..."
-#                 mkdir mindsketch
-#             fi
+      - name: Deploy to VM
+        uses: appleboy/ssh-action@v1.2.1
+        with:
+          host: ${{ secrets.HOST }}
+          username: azureuser
+          key: ${{ secrets.PRIVATE_SSH_KEY }}
+          port: 22
+          script: |
+            #!/bin/bash
+            if [ ! -d "mindsketch" ]; then
+                echo "Creating mindsketch directory..."
+                mkdir mindsketch
+            fi
 
-#             echo "Changing directory to mindsketch..."
-#             cd mindsketch
+            echo "Changing directory to mindsketch..."
+            cd mindsketch
 
-#             echo "Pulling latest image from Docker Hub..."
-#             sudo docker pull abhoy21/mindsketch-ws-server:${{ github.sha }} || {
-#             echo "Error: Failed to pull latest image from Docker Hub"
-#             exit 1
-#             }
+            echo "Pulling latest image from Docker Hub..."
+            sudo docker pull abhoy21/mindsketch-ws-server:${{ github.sha }} || {
+            echo "Error: Failed to pull latest image from Docker Hub"
+            exit 1
+            }
 
-#             echo "Stopping existing container if it exists..."
-#             sudo docker stop ws-server 2>/dev/null || true
+            echo "Stopping existing container if it exists..."
+            sudo docker stop ws-server 2>/dev/null || true
 
-#             echo "Removing existing container if it exists..."
-#             sudo docker rm ws-server 2>/dev/null || true
+            echo "Removing existing container if it exists..."
+            sudo docker rm ws-server 2>/dev/null || true
 
-#             echo "Running docker container..."
-#             sudo docker run -d -p 8080:8080 --name ws-server -e DATABASE_URL=${{ secrets.DATABASE_URL }} -e REDIS_URL=${{secrets.REDIS_URL}} -e JWT_SECRET=${{ secrets.JWT_SECRET }} -e GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }} -e ACCESS_TOKEN_EXPIRES_IN=${{ secrets.ACCESS_TOKEN_EXPIRES_IN }} -e REFRESH_TOKEN_EXPIRES_IN=${{ secrets.REFRESH_TOKEN_EXPIRES_IN }} abhoy21/mindsketch-ws-server:${{ github.sha }} || {
-#             echo "Error: Failed to run docker container"
-#             exit 1
-#             }
+            echo "Running docker container..."
+            sudo docker run -d -p 8080:8080 --name ws-server -e DATABASE_URL=${{ secrets.DATABASE_URL }} -e REDIS_URL=${{secrets.REDIS_URL}} -e JWT_SECRET=${{ secrets.JWT_SECRET }} -e GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }} -e ACCESS_TOKEN_EXPIRES_IN=${{ secrets.ACCESS_TOKEN_EXPIRES_IN }} -e REFRESH_TOKEN_EXPIRES_IN=${{ secrets.REFRESH_TOKEN_EXPIRES_IN }} abhoy21/mindsketch-ws-server:${{ github.sha }} || {
+            echo "Error: Failed to run docker container"
+            exit 1
+            }
